ALTER TABLE "Settings" ADD COLUMN "dateMedicalExam" DATETIME DEFAULT NULL;
ALTER TABLE "Settings" ADD COLUMN "dateBipoExam" DATETIME DEFAULT NULL;
ALTER TABLE "Settings" ADD COLUMN "dateFoniaExam" DATETIME DEFAULT NULL;
ALTER TABLE "Settings" ADD COLUMN "dateAdvanced" DATETIME DEFAULT NULL;
